Apparel360/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user import views as UserViews
from product import views as ProductViews
from django.contrib.auth import views as auth_views, views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('signup/', UserViews.signup_form, name='signup_form'),
    path('p_list/', ProductViews.product_list, name='product_list'),
    path('p_detail/', ProductViews.product_detail, name='product_detail'),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('user_profile/', UserViews.user_update, name = 'user_profile'),
    path('update_user_information', UserViews.user_update, name = 'update_user_information'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "homebase.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <style>
        h1, h2, h3, h4, h5, h6 {
            font-family: 'Ubuntu', sans-serif;
            font-weight: normal;
        }

        a {
            text-decoration: none;
            color: #5993bb;
        }

        a:hover {
            color: #77b6e2;
        }

        a.button, input[type="submit"] {
            color: #fff;
            background: #5993bb;
            border-radius: 4px;
            padding: 10px 20px;
            font-size: 14px;
            border: 0;
        }

        a.button.light {
            color: #666;
            background: #ededed;
        }

        .text-left {
            text-align: left;
        }

        .text-right {
            text-align: right;
        }

        table {
            width: 100%;
            border-spacing: 0;
            border-collapse: collapse;
        }

        table th, table td {
            text-align: left;
            font-size: 14px;
            padding: 3px;
            margin: 0;
        }

        tbody tr:nth-child(odd) {
            background: #efefef;
        }

        tbody tr.subtotal {
            background: #ccc;
        }

        thead th, tbody tr.total {
            background: #c6922e;
            color: #fff;
            font-weight: bold;
        }

        table.cart {
            margin-bottom: 40px;
        }

        table.cart img {
            width: 97px;
        }

        tbody td.num {
            text-align: right;
        }

        td input[type="submit"] {
            font-size: 12px;
            padding: 4px 10px;
        }
    </style>
    <div class="container">
    <h3>Your shopping cart</h3>
    <br>

    <table class="cart">
        <thead>
            <tr>
                <th>Product</th>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="
                                        {% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"
                                     alt="">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post" onchange="submit()">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>
                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                <input type="submit" value="Remove" style="background: #c6922e">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="num" style="text-align: left;">${{ item.price }}</td>
                        <td class="num" style="text-align: left;">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr>
                <td colspan="7"></td>
            </tr>
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num" style="text-align: left;">${{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>
                        "{{ cart.coupon.code }}" coupon
                        ({{ cart.coupon.discount }}% off)
                    </td>
                    <td colspan="4" ></td>
                    <td class="num neg" style="text-align: left;">
                        - ${{ cart.get_discount|floatformat:2 }}
                    </td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>Total Amount</td>
                <td colspan="4"></td>
                <td class="num" style="text-align: left;">${{ cart.get_total_price_after_discount | floatformat:2}}</td>
            </tr>
        </tbody>
    </table>

    <h4>Apply a coupon:</h4>
    <p></p>
    <form action="{% url "coupons:apply" %}" method="post">
        &nbsp;
        {{ coupon_apply_form }}
        &nbsp;
        <input type="submit" class="button" style="background: #c6922e" value="Apply">
        {% csrf_token %}
    </form>
    &nbsp;
    <p class="text-right">
        <a href="{% url "product_list" %}" class="button light">Continue shopping</a>
        <a href="{% url "orders:order_create" %}" class="button" style="background: #c6922e">Checkout</a>
    </p>
    </div>
    &nbsp;
    &nbsp;
{% endblock %}